2024-08-06 09:48:39,961 ; PT3S                                                         ; DEBUG   ; dxAndMxHelperFcts.readDxAndMx: Start.
2024-08-06 09:48:39,962 ; PT3S                                                         ; DEBUG   ; Dx.__init__: Start.#########
2024-08-06 09:48:39,963 ; PT3S                                                         ; DEBUG   ; Dx.__init__: dbFile: c:\users\jablonski\3s\pt3s/Examples/DistrictHeating.db3: Not existing! Suche im uebergeordneten Verz. ...
2024-08-06 09:48:39,964 ; PT3S                                                         ; ERROR   ; Dx.__init__: Exception: Line: 236: <class 'Dx.DxError'>: 'Dx.__init__: dbFile: c:\\users\\jablonski\\3s\\pt3s/Examples/DistrictHeating.db3: Not existing!'
2024-08-06 09:48:39,965 ; PT3S                                                         ; DEBUG   ; Dx.__init__: _Done.#########
2024-08-06 09:48:39,966 ; PT3S                                                         ; ERROR   ; dxAndMxHelperFcts.readDxAndMx: Exception: Line: 1398: <class 'dxAndMxHelperFcts.readDxAndMxError'>: 'dxAndMxHelperFcts.readDxAndMx: dbFile: ..\\Examples\\DistrictHeating.db3: DxError!'
2024-08-06 09:48:39,969 ; PT3S                                                         ; DEBUG   ; dxAndMxHelperFcts.readDxAndMx: _Done.
2024-08-06 12:02:42,442 ; ipykernel.comm                                               ; ERROR   ; No such comm target registered: jupyter.widget.control
2024-08-06 12:02:42,449 ; Comm                                                         ; WARNING ; No such comm: 331897aa-87cd-4e8b-9872-67f72d63e23b
2024-08-06 12:02:42,451 ; Comm                                                         ; DEBUG   ; Current comms: []
Current comms: []
